# Generated by Django 4.0.2 on 2022-02-06 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_ingredient_weigthkg'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='weight_kg',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
