# Generated by Django 4.0.2 on 2022-02-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ingredient_weight_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients_count',
        ),
    ]
